### ISSUE TITLE
Multi-line descriptions are corrupted in SD 

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#80] opened 2020-01-10 14:18 UTC
New line and and carriage return characters are being inserted at strange spots in descriptions. The FSH source code  in PrimaryCancerCondition.  Example from fsh-mcode:

Here's the FSH:

Description: """
Records the history of the primary cancer condition, the original or first tumor in the body (Definition from: [NCI Dictionary of Cancer Terms](https://www.cancer.gov/publications/dictionaries/cancer-terms/def/primary-tumor)). Cancers that are not clearly secondary (i.e., of uncertain origin or behavior) should be documented as primary.

Cancer staging information summarized in this profile should reflect the most recent staging assessment on the patient, and should be updated if and when there is a new staging assessment. Past staging assessments will be preserved in instances of the TNMClinicalStageGroup and/or TNMPathologicalStageGroup, which refer back to PrimaryCancerCondition.

Conformance note: For the code attribute, to be compliant with [US Core Profiles](http://hl7.org/fhir/us/core/STU3/index.html), SNOMED CT must be used unless there is no suitable code, in which case ICD-10-CM can be used.
"""

and here's the resulting description field in SD. Note the \n and \r characters and trucations:

"description": "\necords the history of the primary cancer condition, the original or first tumor in the body (Definition from: [NCI Dictionary of Cancer Terms](https://www.cancer.gov/publications/dictionaries/cancer-terms/def/primary-tumor)). Cancers that are not clearly secondary (i.e., of uncertain origin or behavior) should be documented as primary.\r\n\nancer staging information summarized in this profile should reflect the most recent staging assessment on the patient, and should be updated if and when there is a new staging assessment. Past staging assessments will be preserved in instances of the TNMClinicalStageGroup and/or TNMPathologicalStageGroup, which refer back to PrimaryCancerCondition.\r\n\nonformance note: For the code attribute, to be compliant with [US Core Profiles](http://hl7.org/fhir/us/core/STU3/index.html), SNOMED CT must be used unless there is no suitable code, in which case ICD-10-CM can be used.\r",

**Comment by davidhay25** [comment] 2020-01-25 18:23
I think this is a duplicate of #147 (or #147 is a duplicate of this :) )

**Comment by cmoesel** [comment] 2020-01-25 18:25
I'm not sure.  There are different rules for XHTML than standard text.  So we may need to format them different.  In the XHTML, we just want to strip out all newlines and normalize whitespace (as is done when a browser renders it).  But in text that might be markdown formatted, we need to preserve newlines and at least _some_ whitespace.

**Comment by davidhay25** [comment] 2020-01-25 18:27
true...

**Closed** 2020-01-31 21:41 UTC
Labels: added to backlog, bug
