### ISSUE TITLE
Generated structure definitions differ when using sushi -o option

### ISSUE THREAD

**Issue by aschuler84** [FHIR/sushi#174] opened 2020-02-02 00:17 UTC
When using the sushi command with the `-o` option the resulting structure definitions under `build/input/resources` contain an empty differential element at the bottom of the files.

```
"differential": {
    "element": [  ]
  }
```
Whereas when executing sushi without the `-o` option, the resulting differential is non-empty. This can easily be reproduced using the Jan. 2020 Connectathon example provided via http://build.fhir.org/ig/HL7/fhir-shorthand/tutorial.html

**Comment by aschuler84** [comment] 2020-02-02 00:22
When using the sushi command with the -o option the resulting structure definitions under `build/input/resources` contain an empty differential element at the bottom of the files.

```
"differential": {
    "element": [  ]
  }
```
Whereas when executing sushi without the `-o` option, the resulting differential is non-empty.

**Comment by cmoesel** [comment] 2020-02-03 01:29
Yikes.  That _is_ surprising!  Without looking at the code, I can't even think of how/why that would happen.  Thanks for reporting!

**Comment by cmoesel** [comment] 2020-02-04 02:49
Hi @aschuler84.  I am having trouble reproducing this.  I've tried with my own FSH project, but also with the tutorial project (using the `FishExampleComplete` folder, which by the way, seems to have its own errors).  In either case, when I use the `-o` option, it works as expected: output is placed in the desired folder _and_ the output contains the correct _differential_ elements.

If you can provide any additional tips to reproduce, that would be appreciated.

**Comment by aschuler84** [comment] 2020-02-04 03:03
Hi @cmoesel, we tested it on my colleague's windows laptop. I retested it on my own laptop which is a mac. I just did a fresh install of npm and suhsi. As it turns out it is working on my laptop, however I would like to get back to my colleague and ask him to retry this. I will give you an update as soon as we tested this on his machine.

**Comment by regelkraut** [comment] 2020-02-04 23:44
Hi @cmoesel & @aschuler84 ,
I've just tried to redo the steps I did, but I was also not able to reproduce the initial problem any more.
The following scenarios were tested on a Windows 10 laptop:
- sushi . -o .\Output, where the directory ...\Output already existed
- sushi . -o .\Temp, where the directory ...\Temp did not exist and was created during the process

In bothe cases the differential of the StructureDefinition-fish-patient.json file was populated with:
`"differential": {
    "element": [
      {
        "id": "Observation",
        "path": "Observation"
      }
    ]
  }`

So the initial problem of this ticket seems to be gone. So the only problem that remains with the example is, that the differential contains an "Obersation" instead of the expected "Patient".

**Comment by cmoesel** [comment] 2020-02-05 13:44
I'm glad to look into the Observation vs Patient issue, but I can't reproduce it.  If you want to attach your FSH files here I can take a look.

**Comment by regelkraut** [comment] 2020-02-05 23:41
Sure thing. Attached you'll find the FSH file I used (again as .txt)
[FishPatient.txt](https://github.com/FHIR/sushi/files/4162524/FishPatient.txt)

It's the unchanged file from the sample of the shorthand tutorial from this page on:
[build.fhir.org](http://build.fhir.org/ig/HL7/fhir-shorthand/tutorial.html#step-3-download-sample-fsh-tank)

**Comment by cmoesel** [comment] 2020-02-06 00:47
Oh....  yes, I see it now.  I'm not sure how I missed it before.  That's a definite bug for sure.  Thanks!

**Comment by cmoesel** [comment] 2020-02-06 00:48
But since it's different than the original, and we can't reproduce the originally reported bug, I'm going to close this one and create a new bug for what you'd reported.

**Comment by regelkraut** [comment] 2020-02-06 00:50
Ok, no problem.

**Closed** 2020-02-06 00:52 UTC
Labels: bug
