### ISSUE TITLE
Sushi 0.6.0 should put generated SDs and other artifacts in /build/input/resources by default

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#104] opened 2020-01-18 02:02 UTC
When no `ig-data` directory is present, SUSHI 0.6.0 puts the generated artifacts directly into the /build directory. The IG publisher can't find them there.  The artifacts need to always go in  /build/input/resources directory. 

The workaround is to use the `-o /build/input/resources` option.

Note: This only happens when the `ig-data` directory does not exist, but that is a significant use case for when IG customizations are to be preserved.

**Comment by cmoesel** [comment] 2020-01-21 14:22
This seems to me like asking for SUSHI to change behavior to support what is essentially a workaround because of current (but hopefully short-lived) limitations in SUSHI's IG generation.

The current behavior is by design, as it's assumed that if you don't want to generate an IG, then you don't want to have to dig into the nested structure that only IGs require.

We can change it, but is this really the solution we want, or do we want SUSHI to play better with customized IGs without all the current hoops you still have to jump through when doing it the way that is proposed above?

**Comment by cmoesel** [comment] 2020-01-21 14:23
It's just that for people not interested in generating IGs, having output go to _build/**input**/resoures_ is really confusing!

**Comment by cmoesel** [comment] 2020-01-21 15:38
OK.  After discussion, we'll do this as suggested.

**Comment by ngfreiter** [comment] 2020-01-21 18:01
This was addressed by #109

**Comment by cmoesel** [comment] 2020-01-22 14:38
Re-opening until this is in an official release.

**Comment by cmoesel** [comment] 2020-01-22 22:44
Fixed in 0.6.1

**Closed by cmoesel** 2020-01-22 22:44 UTC
Labels: added to backlog, bug, merged
