### ISSUE TITLE
Sushi doesn't like strings that start with a # as the first character.

### ISSUE THREAD

**Issue by keithboone** [FHIR/sushi#392] opened 2020-04-25 23:18 UTC
They work if I use """, but not "

**Comment by ngfreiter** [comment] 2020-04-27 13:53
The following seems to work for me:
```
Profile: MyPatient
Parent: Patient
* name.family = "#Hi"
```
Maybe it is something more specific to your use case? Do you have an example we could recreate this with?

**Comment by ngfreiter** [comment] 2020-05-04 15:15
@keithboone any updates on this and how we could recreate it?

**Comment by keithboone** [comment] 2020-05-04 15:57
Instance: states-NJ
InstanceOf: Location
Description : "Example Location for the State of New Jersey"
* name = "# Testing Hash Mark\n## Second test"
* id = "states-NJ"


This is the failing instance.

**Comment by ngfreiter** [comment] 2020-05-04 16:34
It seems like the issue is the `\n`, not the `#` at the start of the string. I haven't been able to cause an issue just using `#` with no `\n`, but the following:
```
Instance: states-NJ
InstanceOf: Location
Description: "nonsenese"
* name = "testing \n in this"
```
does cause an error.  Now it seems like you can accomplish the desired goal here using a multiline string:
```
Instance: states-NJ
InstanceOf: Location
Description: "nonsenese"
* name = """
  testing 
  in this"""
```
But, which gives the output in JSON as 
```
{
  "resourceType": "Location",
  "id": "states-NJ",
  "name": "testing \nin this"
}
```

But I'm not entirely sure if we are supposed to be allowing `\n` if someone wants to use `\n` instead of using a multiline string and using enter. I think @cmoesel and @mint-thompson know more about this and may have a better idea of what should be allowed and what is going on here.

**Comment by cmoesel** [comment] 2020-05-04 18:56
The FHIR Shorthand specification doesn't really define any special support for characters like `\n` in strings.  If we want to support something like this, I think we need to consider what special characters are supported and document them as such.  For example `\r`, `\n`, and `\t` might be good candidates -- this would align well with what FHIR allows in strings (although FHIR doesn't explicitly say to use those representations of the characters).

I think this is worth considering, but we also need to think through any possible implications.

**Comment by keithboone** [comment] 2020-05-04 18:58
Since Sushi seems mostly to be focused on JSON representations, I was thinking that it should support the same escape sequences in strings that JSON supports, or at least expect it to.

**Comment by keithboone** [comment] 2020-05-11 22:55
Added to ballot comments.

**Comment by cmoesel** [comment] 2021-09-14 18:00
Closing this as it was fixed a while back.

**Closed by cmoesel** 2021-09-14 18:00 UTC
