### ISSUE TITLE
Nested extension error

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#108] opened 2020-01-21 15:42 UTC
SUSHI is reporting the following error:

error: Cannot resolve element from path: extension[USCoreRace].extension[ombCategory].valueCoding

I'm not sure if the problem is in the FSH or in SUSHI.

**Comment by cmoesel** [comment] 2020-01-21 15:58
Thanks, @markkramerus.  I have a few questions:

1. What is the context?  Is this an instance or profile definition?
2. If an instance, is the instance an instance of a profile that declares the race extension?  I'm not sure that should be _required_ for this to work, but it's good to know if we invetigate.
3. If a profile definition, did you first use a `contains` definition to introduce the US Core Race Extension?
4. Is `USCoreRace` an alias for the US Core Race Extension URL?

Since US Core Race is an external definition, you need to reference it using its id (`us-core-race`), its name (`USCoreRaceExtension`), or its defining URL (`http://hl7.org/fhir/us/core/StructureDefinition/us-core-race`). I found these by looking at the US Core Race Extension [JSON](http://www.hl7.org/fhir/us/core/StructureDefinition-us-core-race.json.html).  `USCoreRace` is not any of those, but if it's an alias for the URL, then I think that should still work.

**Comment by markkramerus** [comment] 2020-01-21 20:27
1. It's an example, mCODEPatientExample02 in the file Examples.fsh
2. The profile does not declare this extension. It comes from US Core Patient (an external dependency).
3. n/a
4. Yes. USCoreRace is defined as an alias for http://hl7.org/fhir/us/core/StructureDefinition/us-core-race

The issue might be the ombCategory. I don't know if the reference done correctly, given the definition of US Core Race complex extension.

**Comment by ngfreiter** [comment] 2020-01-21 20:33
I think the problem is we expect that whatever is within the brackets will be the sliceName of the slice you are trying to refer to. In your case, you are referring the slice via an alias, which resolves to the URL of that slice. You should be able to accomplish what you want by doing this:
```
* extension[race].extension[ombCategory].valueCoding = USCoreRace#2186-5 "Not Hispanic or Latino"
* extension[birthsex] = GENDER#F 
```
This works since "race" and "birthsex" are the relevant sliceNames as defined on the US Core Patient. However, these slice names are difficult to find, you have to dig through the StructDef of US Core Patient to find them. So we still should figure out a way to allow users to accomplish this using syntax like what you were trying to do.

**Comment by cmoesel** [comment] 2020-01-21 20:36
@ngfreiter and I discussed this earlier and decided that he would work on trying to resolve the provided name (in your case `USCoreRace`) to the actual extension definition, then use that to look up what the slice name should be as defined in the original profile.  This would allow you to use the extension's URL, id, name, or an Alias to its URL inside the brackets as above.

**Comment by markkramerus** [comment] 2020-01-22 14:56
I'll put the workaround in place. For now, we should document that the slice name, not the defining URL, should be used. I didn't know that.

**Comment by cmoesel** [comment] 2020-01-22 14:58
OK, but I think this is something we will try to fix sooner than later, so hopefully that documentation will have a short shelf-life.

**Comment by markkramerus** [comment] 2020-01-22 15:34
By the way, the slice name is not as hard to find as you think. It is right there on the "Detailed Descriptions" tab.  For example,  http://hl7.org/fhir/us/core/STU3/StructureDefinition-us-core-patient-definitions.html#Patient.extension:race

**Comment by cmoesel** [comment] 2020-01-22 16:19
Oh.  Well there you go.  You're a primary user, @markkramerus -- what do you think we should do? Should we *require* that slicename be used when referencing an existing extension?  Or do you like the flexibility of being able to use the extension id/name/url if wanted?

**Comment by cmoesel** [comment] 2020-01-22 22:44
Fixed in 0.6.1

**Closed by cmoesel** 2020-01-22 22:44 UTC
Labels: added to backlog, bug, merged

**Comment by davidhay25** [comment] 2020-01-23 18:59
BTW was this intended to solve the issue where there is a 'name conflict' in extensions? The snippet below fails as the name 'country' has been used elsewhere. Can I propose that (at least for extensions) that the 'contains' name is assumed to be the 'url' of the complex extension, and that there is a way of explicitly stating otherwise - as in the second code snippet? 

```javascript
* extension contains
    country 0..1 and
    placeOfBirth 0..1 and
    source 0..1
```

```javascript
* extension contains
    country 0..1 {url of country extension} and
    placeOfBirth 0..1 and
    source 0..1
```

**Comment by cmoesel** [comment] 2020-01-24 03:03
No, this wasn't intended to solve that problem.  That problem is logged separately as #86.

So far we've been trying to be as flexible as possible in allowing people to refer to extensions (and other things) by their id, name, or url (or an alias to the URL).  But this may be a good use case for why that's not always a good idea.  We'll discuss the possibility of requiring that if you want to `contain` external extensions, you must use their URL (or an alias to their URL).
