### ISSUE TITLE
No file name or line number on certain errors

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#102] opened 2020-01-17 22:47 UTC
These error messages do no include line numbers/file names:
* Cannot resolve element from path
* Cannot fix string value
* Cannot bind value set to boolean
Can we sweep the code base and see if there are any others?

**Comment by ngfreiter** [comment] 2020-01-21 12:58
Duplicate of #82

**Comment by cmoesel** [comment] 2020-01-22 13:59
closing as duplicate

**Closed by cmoesel** 2020-01-22 13:59 UTC
