### ISSUE TITLE
Expanding links to FHIR documentation is failing in some cases

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#170] opened 2020-01-30 13:04 UTC
Comment fields with links are causing IGPub errors (see https://github.com/HL7/fhir-ig-publisher/issues/57).  In most cases, the SDs that SUSHI produces have links that already have been resolved to the FHIR spec. For example, in StructureDefinition-CancerGeneticVariant.json, one finds `[definition of modifier extensions](http://hl7.org/fhir/R4/extensibility.html#modifierExtension)`. However, in StructureDefinition-CancerStageParent.json, the same link appears as `[definition of modifier extensions](extensibility.html#modifierExtension)`, i.e., unexpanded. The latter results in an IGPub error when it adds the root URL to become `'http://hl7.org/fhir/R4/StructureDefinition-CancerStageParent.html/extensibility.html#modifierExtension`.

I'm not sure why the expansion is happening in most cases but not for CancerStageParent, but one difference is that CancerStageParent is an abstract profile that serves as the parent to other profiles. That's not a common pattern, so maybe that's a clue.

**Comment by cmoesel** [comment] 2020-01-30 13:26
I have a task lined up for next sprint to consider publishing the diffs only.  If we go in that direction, it would likely take care of this.  The problem w/ selectively modifying individual properties of snapshot elements is that each change is supposed to be reflected in the diff.

Also, it's not just comments.  I saw this happening w/ links in the `requirements` fields too.

**Comment by markkramerus** [comment] 2020-01-30 13:42
But why is this only broken for a very select set of profiles, and ok in others? 
Here's what I am working on for CancerStagingParent. Well beyond comments:
```
// Workaround for bad links in comments
* valueCodeableConcept ^comment = ""
* bodySite ^comment = ""
* focus ^comment = ""
* effective[x] ^comment = ""
* value[x] ^comment = ""
* component.modifierExtension ^requirements = ""
* component.modifierExtension ^comment = ""
* component.modifierExtension ^definition = ""
* modifierExtension ^requirements = ""
* modifierExtension ^comment = ""
* modifierExtension ^definition = ""
* issued ^comment = ""
* component ^notes = ""
* component.value[x] ^notes = ""
```

**Comment by cmoesel** [comment] 2020-01-30 13:47
I don't know why.  We don't do anything different between those profiles, so that's one of the reasons I don't think there is much that we (sushi) could fix.

Also, what you're doing above is likely going to cause a pretty annoying differential.

... and I think this is a duplicate of #128

**Comment by markkramerus** [comment] 2020-01-30 13:55
Actually, it doesn't show up in the diff. And the ONLY profile affected is CancerStageParent and its children.

**Comment by markkramerus** [comment] 2020-01-30 14:14
A rare moment of clarity:  CancerStageParent inherits from Observation, everything else from USCore Observation. That explains the difference.

**Comment by cmoesel** [comment] 2020-01-30 14:17
Interesting -- I'm guessing that technically it is in the diff (if you look at the JSON) but that maybe the publisher is now smart enough not to show diff elements when the only thing that differs doesn't render in the differential table anyway.  It didn't used to be so smart.

**Comment by cmoesel** [comment] 2020-02-17 21:53
Closing as SUSHI 0.9.0 now generates only the differential by default, which resolves the broken URL errors in the snapshot elements.

**Closed** 2020-02-17 21:54 UTC
Labels: duplicate
