### ISSUE TITLE
version of codesystem not supported

### ISSUE THREAD

**Issue by danka74** [FHIR/sushi#473] opened 2020-06-02 20:42 UTC
Dear All,
support for specifying version of a CodeSystem (and possibly other resources) seems missing. Major use cases are for using a SNOMED CT extension (like AU, SE, or US edition) and using any but the latest version of any CodeSystem.
E.g. in FHS.g4 there is no syntax like:
```
* codes from system http://snomed.info/sct version http://snomed.info/sct/45991000052106 where ...
```
The example above is for the Swedish SNOMED CT extension.
Cheers,
Daniel

**Comment by cmoesel** [comment] 2020-06-02 21:16
Hi @danka74.  Thanks for reporting this.

It appears that we have not documented this very well, but you _can_ specify the version of the code system.  You do it by using the [canonical](http://hl7.org/fhir/R4/datatypes.html#canonical) form of the URL, which allows for a version to be specified as a postfix using the vertical bar (`|`) separator.

So, for your example, you'd simply do something like so:
```
* codes from system http://snomed.info/sct|http://snomed.info/sct/45991000052106 where ...
```

**Comment by cmoesel** [comment] 2020-06-02 21:19
@markkramerus -- this is something that SUSHI does that I don't think is noted in the specification.  It probably should be.

**Comment by danka74** [comment] 2020-06-02 21:32
Thanks @cmoesel , I did find this when looking into the code, ValueSetExporter.ts line 55 if I'm not mistaken, after I posted the issue though...

**Comment by danka74** [comment] 2020-06-03 11:09
Tried a token like this:
```
* codes from system http://snomed.info/sct|http://snomed.info/sct/45991000052106 where constraint = "^64691000052109"
```
and I get:
```
error Resolved value "http://snomed.info/sct|http://snomed.info/sct/45991000052106" is not a valid URI.
```

**Comment by cmoesel** [comment] 2020-06-03 12:38
I agree...  That is fishy!  I tested this locally over here (yesterday) and I did _not_ get that error.  I will try again today with your exact example above and see if I can reproduce it.  Sorry for the trouble!

**Comment by ngfreiter** [comment] 2020-06-03 12:40
I've tried to recreate this using this very simple example:
```
ValueSet: MyVS
* codes from system http://snomed.info/sct|http://snomed.info/sct/45991000052106 where constraint = "^64691000052109"
```
and it seems to work fine for me. One thing I am wondering about though is your version of SUSHI. We haven't released a version 2.1.0. We have a version 0.2.1, and we are on version 0.12.7 as of the time of this comment. But either way I suspect you are using an older version of SUSHI, since the issue you are running into *should* have been fixed in 0.12.1.

One thing to be aware of is that we are not "sushi" on npm, someone got there first (although they haven't published in 4 years!). We are "fsh-sushi" https://www.npmjs.com/package/fsh-sushi, so to install the latest version you must do `npm install -g fsh-sushi`. I bring this up because I notice that the latest version of "sushi" (the one that is not us) on npm is 2.1.0. So maybe something got mixed up here?

**Comment by danka74** [comment] 2020-06-03 12:49
Sorry, I was not thining straight about the version, don't know where 2.1.0 came from, probably some other piece of software...:
$ sushi --version
v0.11.1

**Comment by cmoesel** [comment] 2020-06-03 12:52
How about when you run `npm install fsh-sushi`?  Also, I assume that you're _not_ doing a global (`-g`) install on purpose?

**Comment by cmoesel** [comment] 2020-06-03 12:56
Actually, if you're leaving out the `-g`, then it's installing it in a local `node_modules` folder instead of the global one.  When you use `sushi` without specifying a more specific path to `sushi`, you're using the one on your path -- which is quite likely the one in the _global_ `node_modules` folder.

If you *really* don't want to install/update `sushi` globally, then you need to reference the local one like so:
```
node_modules/.bin/sushi -v
```

But I would highly recommend installing/updating it globally, which means you should be installing it like so:
```
npm install -g fsh-sushi
```

**Comment by danka74** [comment] 2020-06-03 12:58
I did do -g and now with fsh-sushi I get fin-tastic results:
Fin-tastic job!                        0 Errors      0 Warnings
Thanks,
Daniel

**Comment by cmoesel** [comment] 2020-06-03 13:05
Ex-shell-ent!

**Closed** 2020-06-03 13:05 UTC
