### ISSUE TITLE
How does one add intro and notes pages to a StructureDefinition page?

### ISSUE THREAD

**Issue by keithboone** [FHIR/sushi#223] opened 2020-02-16 01:42 UTC
I have the following structure in my input folder:
input/resources
  StructureDefinition-ihe-acdc-questionnaire.json
input/pagecontent
  StructureDefinition-ihe-acdc-questionnaire-intro.md
  StructureDefinition-ihe-acdc-questionnaire-notes.md

However, the published IG doesn't include the intro and notes content after I publish.  I cannot tell if this is a "SUSHI" problem or a "IG Publisher" problem.

**Comment by cmoesel** [comment] 2020-02-17 13:33
@jafeltra -- since you worked on this feature, can you take a look at this for @keithboone?

**Comment by jafeltra** [comment] 2020-02-17 16:07
I took a look at this issue @keithboone and I'm having trouble reproducing it. Is the file structure you reference for `input/resources` and `input/pagecontent` the structure that SUSHI generates after it is run on a FSH tank? If so, then what you described seems to be the correct structure that the IG Publisher is expecting to receive, and I would have expected the intro and notes to be included in the page for the Structure Definition "ihe-acdc-questionnaire" in the IG.

If you are still experiencing this issue, would it be possible for you to share the FSH tank you are experiencing the issue with?

**Comment by keithboone** [comment] 2020-02-17 17:01
The project can be found here: https://github.com/IHE/ACDC

The root of my project is my fishtank.  /build/input is what Sushi produces.  /ig-data/input Is the input I gave it for extra files.  /input is what actually gets submitted to the IG Builder.

            Keith



Keith Boone, Enterprise Architect
kboone@ainq.com | (617) 640-7007

AUDACIOUS INQUIRY
Bold Solutions for Connected Healthcare®
ainq.com<https://ainq.com/>|Twitter<https://twitter.com/a_inq>|YouTube<https://www.youtube.com/channel/UCF-wA3wcjce8YniZhxy1O4Q>|Facebook<https://www.facebook.com/AudaciousInquiry/>| LinkedIn<https://www.linkedin.com/company/audacious-inquiry-llc>

**Comment by jafeltra** [comment] 2020-02-17 17:48
Thanks for the additional information @keithboone. I think the issue is with the additional file that you have in `ig-data/input/pagecontent`. It looks like the file there is an HTML (`.html`) file and the file name starts with a period (`.`). SUSHI supports intro and notes files with two requirements:
- They must be of type markdown (`.md`) or XHTML (`.xml`). 
- The start of the file name should match the resource you want to add the intro or note to, allowing the IG Publisher to match the intro/note to the right resource.

In your intro file, if you change the file type to either `.md` or `.xml`, it will be in a supported type. Also, if you remove the `.` at the start of the file name, it will match the resource it should be added to. Making these two changes and rebuilding and publishing should allow the intro to be included on the resource.

Hopefully this helps! If it still doesn't seem to work, please just let us know.

**Comment by jafeltra** [comment] 2020-02-27 21:38
Were you ever able to confirm if this fix worked for your intro and notes pages @keithboone? If so, can I close this issue?

**Comment by keithboone** [comment] 2020-02-28 02:36
Yes


Keith Boone, Enterprise Architect
kboone@ainq.com | (617) 640-7007

AUDACIOUS INQUIRY
Bold Solutions for Connected Healthcare®
ainq.com<https://ainq.com/>|Twitter<https://twitter.com/a_inq>|YouTube<https://www.youtube.com/channel/UCF-wA3wcjce8YniZhxy1O4Q>|Facebook<https://www.facebook.com/AudaciousInquiry/>| LinkedIn<https://www.linkedin.com/company/audacious-inquiry-llc>

**Comment by jafeltra** [comment] 2020-02-28 13:32
Great! Glad to hear it!

**Closed by jafeltra** 2020-02-28 13:32 UTC
