### ISSUE TITLE
FHIR IG Publisher Version 1.1.79 Exception generating resource error for value set

### ISSUE THREAD

**Issue by dmangum2** [FHIR/sushi#914] opened 2021-09-03 19:36 UTC
Not sure if this is a sushi or publisher error.

FHIR IG Publisher Version 1.1.79 error and didn't get in 1.1.77

Exception generating resource C:....\build\input\vocabulary\valueset-appointment-cancellation-reason::ValueSet/appointment-cancellation-reason: The workbook already contains a sheet named 'Include from Appointment Cancellation Reason Codes' (02:56.0085)
java.lang.IllegalArgumentException: The workbook already contains a sheet named 'Include from Appointment Cancellation 
Reason Codes'
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.validateSheetName(XSSFWorkbook.java:910)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.createSheet(XSSFWorkbook.java:863)
        at org.hl7.fhir.r5.renderers.spreadsheets.ValueSetSpreadsheetGenerator.genIncludeSystem(ValueSetSpreadsheetGenerator.java:117)
        at org.hl7.fhir.r5.renderers.spreadsheets.ValueSetSpreadsheetGenerator.genInclude(ValueSetSpreadsheetGenerator.java:87)
        at org.hl7.fhir.r5.renderers.spreadsheets.ValueSetSpreadsheetGenerator.renderValueSet(ValueSetSpreadsheetGenerator.java:40)
        at org.hl7.fhir.igtools.publisher.Publisher.generateOutputsValueSet(Publisher.java:7815)
        at org.hl7.fhir.igtools.publisher.Publisher.generateResourceHtml(Publisher.java:6882)
        at org.hl7.fhir.igtools.publisher.Publisher.generateHtmlOutputs(Publisher.java:6840)
        at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:5052)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:908)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:752)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8664)
   org.apache.poi.xssf.usermodel.XSSFWorkbook.validateSheetName(XSSFWorkbook.java:910) (02:56.0130)
   org.apache.poi.xssf.usermodel.XSSFWorkbook.createSheet(XSSFWorkbook.java:863) (02:56.0134)
   org.hl7.fhir.r5.renderers.spreadsheets.ValueSetSpreadsheetGenerator.genIncludeSystem(ValueSetSpreadsheetGenerator.java:117) (02:56.0138)
   org.hl7.fhir.r5.renderers.spreadsheets.ValueSetSpreadsheetGenerator.genInclude(ValueSetSpreadsheetGenerator.java:87) (02:56.0141)
   org.hl7.fhir.r5.renderers.spreadsheets.ValueSetSpreadsheetGenerator.renderValueSet(ValueSetSpreadsheetGenerator.java:40) (02:56.0145)
   org.hl7.fhir.igtools.publisher.Publisher.generateOutputsValueSet(Publisher.java:7815) (02:56.0149)
   org.hl7.fhir.igtools.publisher.Publisher.generateResourceHtml(Publisher.java:6882) (02:56.0152)
   org.hl7.fhir.igtools.publisher.Publisher.generateHtmlOutputs(Publisher.java:6840) (02:56.0154)
   org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:5052)        (02:56.0156)
   org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:908)         (02:56.0159)
   org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:752)          (02:56.0161)
   org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:8664)            (02:56.0165)

AppointmentCancellationReasonCodes.fsh:
CodeSystem:     AppointmentCancellationReasonCodeSystem
Id:             appointment-cancellation-reason
Title:          "Appointment Cancellation Reason Codes"
Description:    "Extended reasons for the cancellation of an appointment"
* #deleted      "Deleted"       "Appointment was either logically deleted or physically deleted"
* #rescheduled  "Rescheduled"   "Appointment was rescheduled"

ValueSet:     AppointmentCancellationReasonValueSet
Id:             appointment-cancellation-reason
Title:          "Appointment Cancellation Reason Value Set"
Description:    "Extended set of reasons for the cancellation of an appointment"
* codes from system http://terminology.hl7.org/CodeSystem/appointment-cancellation-reason
* codes from system AppointmentCancellationReasonCodeSystem

No such message in the QA Report
Using sushi v0.16.0; also tried sushi 2.0.1

**Comment by cmoesel** [comment] 2021-09-07 12:15
Hi @dmangum2.  I have never seen this error before.  It is an interesting one.  I was able to reproduce it locally, and it seems it has to do with this line specifically:
```
* codes from system http://terminology.hl7.org/CodeSystem/appointment-cancellation-reason
```
I don't know why including codes from this system into your own value set causes the error `The workbook already contains a sheet named 'Include from Appointment Cancellation Reason Codes'`.  This may be something we'd have to ask @grahamegrieve about.

I did find, however, that if you include those codes using the _value set_ instead of the _code system_, that it seems to work fine.  So I would replace the problematic line above with this one instead:
```
* codes from valueset http://terminology.hl7.org/ValueSet/appointment-cancellation-reason
```

Since the Appointment Cancellation Reason value set should contain all the codes in the Appointment Cancellation Reason code system, including by the value set should be equivalent and get you what you need.

**Comment by cmoesel** [comment] 2021-09-07 12:23
Thanks for the quick response and confirmation, Grahame!

**Comment by dmangum2** [comment] 2021-09-07 12:57
Thank you for the updates and workaround. Should I leave the issue open until fixed?

**Comment by cmoesel** [comment] 2021-09-07 13:04
Since this is an issue with the IG Publisher, and not SUSHI, I'm going to go ahead and close it now.  Thanks!

**Closed by cmoesel** 2021-09-07 13:04 UTC
