### ISSUE TITLE
Validating extensions during instance generation

### ISSUE THREAD

**Issue by davidhay25** [FHIR/sushi#136] opened 2020-01-24 02:28 UTC
If you add an extension to an instance, sushi doesn;'t validate that the extension instance data is compliant with the extension definition

**Comment by cmoesel** [comment] 2020-01-24 02:57
A few followup questions to help us reproduce/debug:

1. Is the extension a declared extension in the profile you're creating an instance of (for example, using a US Core Race extension on an instance of US Core Patient)? Or are you using an extension where it's allowed, but perhaps not declared (for example, using a US Core Race extension on an instance of plain old Patient)?

2. What type of validation are we talking about?  Type validation (e.g., it allows `valueQuantity` where only `valueCodeableConcept` is allowed), value set validation (using a code not in the allowed value set), or validation against a FHIRPath constraint?  SUSHI isn't (currently) designed to validate codes or invariants -- but it is intended to validate that you at least use a valid type and obey cardinality (although the cardinality bit might not be implemented yet).

**Comment by davidhay25** [comment] 2020-01-24 17:44
Does this help? Note that the extension definition has 'periodXXX' (as I can't use 'period') but the instance has 'period' ...  (I'm using XXX to mark extension names that are currently not allowed as someone else in the world has used it! = #86) 

Extension definition:
```
Extension: practitioner-conditions-on-practice
Id: practitioner-conditions-on-practice
Description:  "None supplied yet"
//These files were generated by a script

* extension contains
    description 0..1 and
    periodXXX 0..1

// definitions of sub-extensions
* extension[description].url = "description"
* extension[description] ^definition = "The condition on practice as text"
* extension[description].value[x] only string

* extension[periodXXX].url = "periodXXX"
* extension[periodXXX] ^definition = "The period the conditions on practice are effective"
* extension[periodXXX].value[x] only Period
```

Instance:
```
//there is a condition on practice
* qualification[0].extension[2].url = "http://hl7.org.nz/fhir/StructureDefinition/practitioner-conditions-on-practice"
* qualification[0].extension[2].extension[0].url = "description"
* qualification[0].extension[2].extension[0].valueString = "Dr Example  is permitted to practise medicine in the position of House Officer in accredited clinical attachments at Southern District Health Board under the supervision of an approved prevocational educational supervisor between 01 March 2019 and 30 November 2019. The purpose of this registration is to require doctors to meet Council requirements for registration in the general scope of practice."
* qualification[0].extension[2].extension[1].url = "period"
* qualification[0].extension[2].extension[1].valuePeriod.start = "2018-11-26"
* qualification[0].extension[2].extension[1].valuePeriod.end = "2019-03-01"
```

**Comment by cmoesel** [comment] 2020-01-25 00:19
OK, yes that does help.  And you're right, if you put in extension data manually (like above), we don't really validate the content at all.  But if you use our special syntax for setting extensions, there is a bit more validation done.  For example, this is another way to do the _correct_ version of above:

```
Profile: PractitionerProfile
Parent: Practitioner
* qualification.extension contains practitioner-conditions-on-practice 0..*

Instance: MyPractitioner2
InstanceOf: PractitionerProfile
* qualification[0].extension[practitioner-conditions-on-practice].extension[description].valueString = "Dr Example  is permitted to practise medicine in the position of House Officer in accredited clinical attachments at Southern District Health Board under the supervision of an approved prevocational educational supervisor between 01 March 2019 and 30 November 2019. The purpose of this registration is to require doctors to meet Council requirements for registration in the general scope of practice."
* qualification[0].extension[practitioner-conditions-on-practice].extension[periodXXX].valuePeriod.start = "2018-11-26"
* qualification[0].extension[practitioner-conditions-on-practice].extension[periodXXX].valuePeriod.end = "2019-03-01"
```

If you use this approach and mess up the extension name, it reports an error:

```
// most same as above except:
* qualification[0].extension[practitioner-conditions-on-practice].extension[period].valuePeriod.end = "2019-03-01"
// error: Cannot resolve element from path: qualification[0].extension[practitioner-conditions-on-practice].extension[period].valuePeriod.end
```
Note that this only works when you're using that approach and furthermore only if the profile specified that it allowed that extension (e.g., you couldn't use that extension that way on a plain `Practitioner` instance).  This is a current limitation.

**Comment by davidhay25** [comment] 2020-01-25 02:49
Ah - good point. I'll re-work my profiles. thanks!

**Comment by davidhay25** [comment] 2020-01-26 20:25
BTW - if you do use the special syntax (?ginzu) then you can't combine it
with the manual way of specifying extensions in the same instance.
sushi gets quite confused...

**Comment by davidhay25** [comment] 2020-01-26 20:48
bbtw - also, you can't have more than one instance of the same extension
type - eg the following will only have a single extension (the second) in
the instance...

//there is a condition on practice
*
qualification[0].extension[practitioner-conditions-on-practice].extension[description].valueString
= "Dr Example is permitted to practise medicine in the position of House
Officer in accredited clinical attachments at Southern District Health
Board under the supervision of an approved prevocational educational
supervisor between 01 March 2019 and 30 November 2019. The purpose of this
registration is to require doctors to meet Council requirements for
registration in the general scope of practice."
*
qualification[0].extension[practitioner-conditions-on-practice].extension[periodXXX].valuePeriod.start
= "2018-11-26"
*
qualification[0].extension[practitioner-conditions-on-practice].extension[periodXXX].valuePeriod.end
= "2019-03-01"

//there is a condition on practice
*
qualification[0].extension[practitioner-conditions-on-practice].extension[description].valueString
= "test"
*
qualification[0].extension[practitioner-conditions-on-practice].extension[periodXXX].valuePeriod.start
= "2018-11-26"
*
qualification[0].extension[practitioner-conditions-on-practice].extension[periodXXX].valuePeriod.end
= "2019-03-01"

**Comment by cmoesel** [comment] 2020-01-26 21:47
Ah...  Good point.  Hmmm...  So I think if we want to support something like this, we would require an indexer for the second instance.  So something like:
```
// first condition (indexer [0] is optional, but we'll use it)
*
qualification[0].extension[practitioner-conditions-on-practice][0].extension[description].valueString
= "desc1"
*
qualification[0].extension[practitioner-conditions-on-practice][0].extension[periodXXX].valuePeriod.start
= "2018-11-26"
*
qualification[0].extension[practitioner-conditions-on-practice][0].extension[periodXXX].valuePeriod.end
= "2019-03-01"

// second condition
*
qualification[0].extension[practitioner-conditions-on-practice][1].extension[description].valueString
= "test"
*
qualification[0].extension[practitioner-conditions-on-practice][1].extension[periodXXX].valuePeriod.start
= "2018-11-26"
*
qualification[0].extension[practitioner-conditions-on-practice][1].extension[periodXXX].valuePeriod.end
= "2019-03-01"
```

I don't know that this works now (kind of guessing no), but it's the basic idea.

**Comment by davidhay25** [comment] 2020-01-26 22:49
Actually - it works!   now all you need to do is update the documentation .
:)

**Comment by cmoesel** [comment] 2020-01-27 00:52
Oh good!  @ngfreiter will be glad to hear that since he was the one who worked on this specific stuff.  Nick, I should have never doubted -- I just thought that maybe since it was mixing extensions *and* slice-specific indexers at the same time it might expose some edge cases.  But I guess not!  Nice work!

**Comment by davidhay25** [comment] 2020-01-27 06:49
I'm obviously going to have to work harder to break it!

**Comment by ngfreiter** [comment] 2020-05-04 16:53
This issue looks like it was resolved, so I am closing.

**Closed by ngfreiter** 2020-05-04 16:53 UTC
