### ISSUE TITLE
Support other systems in Quantity value syntax

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#729] opened 2021-01-14 14:23 UTC
currently, FSH only allows a single line syntax for quantities when the unit is UCUM.  E.g., this:
```
* valueQuantity = 55 'mm' "millimeters"
```
Anything inside `'` `'` is expected to be UCUM.  If the unit is not ucum, you need to do it more like this:
```
* valueQuantity = http://mysystem.org/codes#foo "Foos"
* valueQuantity.value = 42
```

I think for STU2 we should support this syntax for the latter:
```
* valueQuantity = 42 http://mysystem.org/codes#foo "Foos"
```
Of course, aliases would be supported too:
```
* valueQuantity = 42 MYSYS#foo "Foos"
```

**Comment by jafeltra** [comment] 2024-09-10 19:52
This appears to be a duplicate of #730, which is done.

**Closed by jafeltra** 2024-09-10 19:52 UTC
Labels: added to backlog
